travis:
  secure:
    BINSTAR_TOKEN: EO6qOjZmCEt5W/fYmJKkXxRc9Tuc+i3kFHuVRXaeRgKM/zzuojW291eWZ0KZqQ7tlj/A2AmUe8iOqmBYT9nJjj8LWqGMPk4e4rlnmV5Gf6ISdJt0fknU2lmUWvgiloOxxpgbVG75miqYIPjw9zdAfgC+GMX+7yOqAz++gB5O3wObjpkoyYMG+grKhp46ICYxMib4VRxr+qEwBuRBQ3exjo8iD5eexr9UwCuGW8pQkx3mfbOPdKVX74l1T2vh1Fk396j+ImnoSARaPyS9eRLRKbgo83vefvZMNs853KzQfZ2EL3P17iktSS+gkoK5H0u3m8VpOn1N35fMtpMh1kLENrBpKC0WXTQ4KOIfBCvzAf1PaxkdL5d+ZizIU8FRRa6Q/CQD3FTy13bclgyqYlAgHkWnHLWXGznEw9t+826efRXZRJrgYMdhFcoM+ElOO6ZyNAxIIiG4g/xCXmdsaVe6K1y7/xoGgiOcEl16/gMsWD4ZjNnU8QqXNfbEUIg8fMiymYjrj0t0N23X/e78RKBx39pNLfH32lQdzkDFl7NMKUimtCnSLtHk1fBEtJ1Z2IulcEwz57DcQBMFVQwIzsoUxdL4NHgM7kwIhY8Aar/T96C+gBMMtagf54vRgGJQ4s1sROqGRqzflcYSj4sbktGvukfckXFG1mrmlSfDj3EZ1r4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
